<?php
/**
 * @file
 * net_reyero_devel install file
 */

/**
 * Implements hook_enable().
 */
function net_reyero_devel_enable() {
  // Disable modules
  module_disable(array(
    'net_reyero_live',
  ));

  // Set variables
  variable_set('cache', 0);
  variable_set('block_cache', FALSE);
  variable_set('page_compression', FALSE);
  variable_set('preprocess_css', 0);
  variable_set('preprocess_js', 0);
  variable_set('error_level', ERROR_REPORTING_DISPLAY_ALL);
}

