<?php
/**
 * @param
 * Reyero.net: Custom modules base API and tools
 */

/**
 * Implements hook_system_info_alter()
 */
function net_reyero_custom_system_info_alter(&$info, $file, $type) {
  $custom_projects = &drupal_static('net_reyero_custom_projects', array('custom'));
  // Mark some modules as belonging to the 'net_reyero' package:
  // - Modules in sites/all/modules/custom
  // - Module info file contains 'custom = true'
  if (!empty($info['custom']) || $type == 'module' && preg_match('/^sites\/all\/modules\/custom/', $file->filename)) {
    if (!empty($info['project'])) {
      $custom_projects[] = $info['project'];
    }
    else {
      $info['project'] = 'custom';
    }
  }
}

/**
 * Implements hook_update_projects_alter().
 */
function net_reyero_custom_update_projects_alter(&$projects) {
  $custom_projects = &drupal_static('net_reyero_custom_projects', array('custom'));
  // Remove custom projects from drupal.org updates.
  if (!empty($custom_projects)) {
    foreach (array_unique($custom_projects) as $name) {
      unset($projects[$name]);
    }
  }
}

/**
 * Implements hook_l10n_update_projects_alter().
 */
function net_reyero_custom_l10n_update_projects_alter(&$projects) {
  // Remove custom projects from drupal.org updates.
  net_reyero_custom_update_projects_alter($projects);
}